Practiced numpy basics using Python for Data Science Cheat sheet by DataCamp

In [158]:
import numpy as np

In [5]:
#Creating arrays
a= np.array([1,2,3]) 

In [6]:
a

array([1, 2, 3])

In [7]:
b = np.array([(1,2,3),(6,7,8)])

In [8]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [9]:
b = np.array([(1,2,3),(2,3,4)], dtype=float)

In [10]:
b

array([[1., 2., 3.],
       [2., 3., 4.]])

In [32]:
#Initial placeholder
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
 c= np.ones((2,3,4), dtype= np.int16)

In [14]:
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [15]:
d = np.arange(10,25,5)

In [16]:
d

array([10, 15, 20])

In [17]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
e = np.full((2,2),7)

In [19]:
e

array([[7, 7],
       [7, 7]])

In [20]:
f= np.eye(2)

In [21]:
f

array([[1., 0.],
       [0., 1.]])

In [22]:
np.random.random((2,2))

array([[0.27221117, 0.6229883 ],
       [0.68710112, 0.22246539]])

In [23]:
np.empty((3,2))

array([[1., 2.],
       [3., 2.],
       [3., 4.]])

In [24]:
b.shape

(2, 3)

In [25]:
len(b)

2

In [26]:
b.ndim

2

In [27]:
c.shape

(2, 3, 4)

In [28]:
len(c)

2

In [29]:
c.ndim

3

In [30]:
e.size

4

In [33]:
b.dtype

dtype('float64')

In [34]:
e.dtype


dtype('int32')

In [35]:
b.dtype.name

'float64'

In [39]:
b.astype(str)

array([['1.0', '2.0', '3.0'],
       ['2.0', '3.0', '4.0']], dtype='<U32')

In [40]:
b

array([[1., 2., 3.],
       [2., 3., 4.]])

In [46]:
np.info(len)

Return the number of items in a container.


In [47]:
g= a-b

In [48]:
g

array([[ 0.,  0.,  0.],
       [-1., -1., -1.]])

In [49]:
np.subtract(a,b)

array([[ 0.,  0.,  0.],
       [-1., -1., -1.]])

In [51]:
np.exp(b)

array([[ 2.71828183,  7.3890561 , 20.08553692],
       [ 7.3890561 , 20.08553692, 54.59815003]])

In [52]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ]])

In [53]:
np.sin(b)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.90929743,  0.14112001, -0.7568025 ]])

In [54]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.41614684, -0.9899925 , -0.65364362]])

In [55]:
np.log(b)

array([[0.        , 0.69314718, 1.09861229],
       [0.69314718, 1.09861229, 1.38629436]])

In [56]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [57]:
a==b

array([[ True,  True,  True],
       [False, False, False]])

In [58]:
a<2

array([ True, False, False])

In [60]:
a

array([1, 2, 3])

In [61]:
b


array([[1., 2., 3.],
       [2., 3., 4.]])

In [62]:
a.sum()

6

In [63]:
a.min()

1

In [69]:
a.max(axis=0)

3

In [72]:
b.cumsum(axis =1)

array([[1., 3., 6.],
       [2., 5., 9.]])

b.mean()

In [76]:
b.mean()


2.5

In [78]:
np.std(b)

0.9574271077563381

In [79]:
h=a.view()

In [80]:
h

array([1, 2, 3])

In [81]:
h=h+1

In [82]:
h

array([2, 3, 4])

In [83]:
a

array([1, 2, 3])

In [84]:
h=a.view()

In [85]:
h

array([1, 2, 3])

In [86]:
np.copy(a)

array([1, 2, 3])

In [87]:
h= a.copy()

In [88]:
h

array([1, 2, 3])

In [89]:
a.sort()

In [90]:
a

array([1, 2, 3])

In [91]:
c.sort(axis=0)

In [92]:
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [101]:
k = np.array([(1,2,3),(8,9,10)])

In [103]:
k

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [105]:
k[0]

array([1, 2, 3])

In [106]:
k[1,2]

10

In [107]:
k[0:2,1]

array([2, 9])

In [109]:
k[::-1]

array([[ 8,  9, 10],
       [ 1,  2,  3]])

In [110]:
k.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10]])

In [111]:
k

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [112]:
np.transpose(k)

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10]])

In [113]:
#changing array shape

In [115]:
k.ravel() #flatten the array

array([ 1,  2,  3,  8,  9, 10])

In [125]:
k.reshape(3,2)

array([[ 1,  2],
       [ 3,  8],
       [ 9, 10]])

In [123]:
k.reshape(1,6)

array([[ 1,  2,  3,  8,  9, 10]])

In [126]:
#adding and removing elements

In [132]:
k

array([[ 1,  2],
       [ 3,  8],
       [ 9, 10]])

In [130]:
k.resize((3,2)) #changes the original k

In [131]:
k

array([[ 1,  2],
       [ 3,  8],
       [ 9, 10]])

In [133]:
np.append(k,g)

array([ 1.,  2.,  3.,  8.,  9., 10.,  0.,  0.,  0., -1., -1., -1.])

In [134]:
g

array([[ 0.,  0.,  0.],
       [-1., -1., -1.]])

In [136]:
np.insert(k,3,5)

array([ 1,  2,  3,  5,  8,  9, 10])

In [139]:
np.delete(k,[2])

array([ 1,  2,  8,  9, 10])

In [140]:
k

array([[ 1,  2],
       [ 3,  8],
       [ 9, 10]])

In [144]:
#combining arrays
k.resize(2,3)
np.concatenate((g,k))

array([[ 0.,  0.,  0.],
       [-1., -1., -1.],
       [ 1.,  2.,  3.],
       [ 8.,  9., 10.]])

In [145]:
np.vstack((g,g))

array([[ 0.,  0.,  0.],
       [-1., -1., -1.],
       [ 0.,  0.,  0.],
       [-1., -1., -1.]])

In [146]:
np.r_[k,g]

array([[ 1.,  2.,  3.],
       [ 8.,  9., 10.],
       [ 0.,  0.,  0.],
       [-1., -1., -1.]])

In [147]:
k

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [148]:
g

array([[ 0.,  0.,  0.],
       [-1., -1., -1.]])

In [149]:
np.hstack((k,g))

array([[ 1.,  2.,  3.,  0.,  0.,  0.],
       [ 8.,  9., 10., -1., -1., -1.]])

In [150]:
np.column_stack((k,g))

array([[ 1.,  2.,  3.,  0.,  0.,  0.],
       [ 8.,  9., 10., -1., -1., -1.]])

In [151]:
np.c_[k,g]

array([[ 1.,  2.,  3.,  0.,  0.,  0.],
       [ 8.,  9., 10., -1., -1., -1.]])

Splitting arrays

In [156]:
np.hsplit(k,3)

[array([[1],
        [8]]), array([[2],
        [9]]), array([[ 3],
        [10]])]

In [153]:
np.vsplit(k,2)

[array([[1, 2, 3]]), array([[ 8,  9, 10]])]

In [157]:
k

array([[ 1,  2,  3],
       [ 8,  9, 10]])