Reference: Python for Data Science Cheat Sheet SciPy- Linear Algebra
www.datacamp.com

In [1]:
import numpy as np


In [2]:
a= np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b= np.array([(1+2j,2j,3j),(4j,5j,6j)])

In [5]:
b

array([[1.+2.j, 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])

In [6]:
b.shape

(2, 3)

In [7]:
c = np.array([[(1.5,2,3),(4,5,6),[(3,2,1),(4,5,6)]]])

In [8]:
c

array([[(1.5, 2, 3), (4, 5, 6), list([(3, 2, 1), (4, 5, 6)])]],
      dtype=object)

In [9]:
c.shape

(1, 3)

In [10]:
d= np.mgrid[0:5,0:5]

In [11]:
d.shape

(2, 5, 5)

In [12]:
d

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [13]:
d = np.ogrid[0:2,0:2]

In [14]:
d

[array([[0],
        [1]]), array([[0, 1]])]

In [15]:
np.r_[3,[0]*5,-5:5:3]

array([ 3,  0,  0,  0,  0,  0, -5, -2,  1,  4])

In [16]:
np.r_[3,[0]*5,-5:5:3j]

array([ 3.,  0.,  0.,  0.,  0.,  0., -5.,  0.,  5.])

In [17]:
#shape manipulation

In [18]:
e = np.array([[1,2,3],[4,5,6]])

In [19]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
e.shape

(2, 3)

In [21]:
np.transpose(e)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [23]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
f = np.array([[8,9,0],[5,6,7]])

In [25]:
f

array([[8, 9, 0],
       [5, 6, 7]])

In [26]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.hstack((e,f))

array([[1, 2, 3, 8, 9, 0],
       [4, 5, 6, 5, 6, 7]])

In [28]:
h =np.vstack((e,f))

In [29]:
h

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0],
       [5, 6, 7]])

In [30]:
np.vsplit(h,2)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[8, 9, 0],
        [5, 6, 7]])]

In [31]:
np.hsplit(h,1)

[array([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 0],
        [5, 6, 7]])]

In [32]:
#polynomials

In [33]:
from numpy import poly1d

In [34]:
p = poly1d([3,4,5])

In [35]:
p

poly1d([3, 4, 5])

In [36]:
#vectorization function
def myfunc(a):
    if a<0:
        return a*2
    else:
        return a/2

In [37]:
np.vectorize(myfunc)

In [38]:
#type handling

In [39]:
np.real(b)

array([[1., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.imag(b)

array([[2., 2., 3.],
       [4., 5., 6.]])

In [41]:
b

array([[1.+2.j, 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])

In [42]:
np.real_if_close(c,tol=1000)

array([[(1.5, 2, 3), (4, 5, 6), list([(3, 2, 1), (4, 5, 6)])]],
      dtype=object)

In [43]:
np.cast['f'](np.pi)

array(3.1415927, dtype=float32)

In [44]:
#other useful functions

In [45]:
np.angle(b,deg = True)

array([[63.43494882, 90.        , 90.        ],
       [90.        , 90.        , 90.        ]])

In [46]:
g = np.linspace(0, np.pi, num = 5)

In [47]:
g

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [48]:
g[3:] +=np.pi

In [49]:
g

array([0.        , 0.78539816, 1.57079633, 5.49778714, 6.28318531])

In [50]:
np.unwrap(g)

array([ 0.        ,  0.78539816,  1.57079633, -0.78539816,  0.        ])

In [51]:
np.logspace(0,10,3)

array([1.e+00, 1.e+05, 1.e+10])

In [52]:
np.select([b<2],[b*2])

array([[2. +4.j, 0. +4.j, 0. +6.j],
       [0. +8.j, 0.+10.j, 0.+12.j]])

In [53]:
b

array([[1.+2.j, 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])

In [54]:
c

array([[(1.5, 2, 3), (4, 5, 6), list([(3, 2, 1), (4, 5, 6)])]],
      dtype=object)

In [55]:
a

array([1, 2, 3])

In [56]:
from scipy import linalg, sparse

In [57]:
A = np.matrix(np.random.random((2,2)))

In [58]:
A

matrix([[0.25415886, 0.26913639],
        [0.15352322, 0.54431044]])

In [59]:
B = np.asmatrix(b)

In [60]:
B

matrix([[1.+2.j, 0.+2.j, 0.+3.j],
        [0.+4.j, 0.+5.j, 0.+6.j]])

In [61]:
b

array([[1.+2.j, 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])

In [62]:
C = np.mat(np.random.random((10,5)))

In [63]:
C

matrix([[0.82218574, 0.06715753, 0.84371468, 0.78440323, 0.49341775],
        [0.37923314, 0.52877533, 0.63606593, 0.55575288, 0.02122977],
        [0.22606288, 0.96935041, 0.53320715, 0.97877758, 0.03141008],
        [0.67415834, 0.14676308, 0.1040982 , 0.24751765, 0.28636875],
        [0.75758039, 0.05852692, 0.39133547, 0.00286976, 0.01824493],
        [0.14448282, 0.3590481 , 0.84756874, 0.49931005, 0.74171086],
        [0.14408438, 0.04257288, 0.82920396, 0.95738465, 0.40586522],
        [0.46324691, 0.97189863, 0.120752  , 0.12879587, 0.62879445],
        [0.52074688, 0.78336752, 0.20674727, 0.53523579, 0.31689978],
        [0.74495885, 0.76342509, 0.6452048 , 0.62757448, 0.57529592]])

In [64]:
D = np.mat([[3,4],[5,6]])

In [65]:
D

matrix([[3, 4],
        [5, 6]])

In [66]:
#basic matrix operations

In [67]:
A

matrix([[0.25415886, 0.26913639],
        [0.15352322, 0.54431044]])

In [68]:
A.I

matrix([[ 5.61013878, -2.77395464],
        [-1.58234443,  2.61958314]])

In [69]:
linalg.inv(A)

array([[ 5.61013878, -2.77395464],
       [-1.58234443,  2.61958314]])

In [70]:
#transposition
A.T

matrix([[0.25415886, 0.15352322],
        [0.26913639, 0.54431044]])

In [71]:
A.H #conjugate transposition

matrix([[0.25415886, 0.15352322],
        [0.26913639, 0.54431044]])

In [72]:
np.trace(A)

0.7984693008655949

#norm

In [73]:
linalg.norm(A)

0.6759248174543958

In [74]:
linalg.norm(A,1)

0.8134468302297564

In [75]:
linalg.norm(A,np.inf)

0.6978336685025902

In [76]:
#rank
np.linalg.matrix_rank(C)

5

In [77]:
#determinant
linalg.det(A)

0.09702263436929272

In [78]:
#solving linear problems
linalg.solve(A,b)

array([[ 5.61013878 +0.12445903j,  0.         -2.64949561j,
         0.         +0.18668854j],
       [-1.58234443 +7.3136437j ,  0.         +9.93322684j,
         0.        +10.97046555j]])

In [79]:
E = np.mat(a).T

In [80]:
a

array([1, 2, 3])

In [81]:
E

matrix([[1],
        [2],
        [3]])

In [82]:
#generalised inverse
linalg.pinv(C)

array([[ 0.34329464, -0.01669875, -0.14262709,  0.49251876,  0.46172214,
        -0.45952021, -0.19149618, -0.03849985,  0.17760585,  0.12595034],
       [-0.42474817,  0.34299157,  0.34013561, -0.32326703,  0.10733449,
         0.12515799, -0.36212687,  0.37618471,  0.08544296,  0.12646045],
       [-0.15063371,  0.8040288 , -0.06065989, -0.77883201,  0.79470985,
         0.7765395 , -0.16882859, -0.13195317, -0.61673803,  0.06720802],
       [ 0.34392536, -0.43440415,  0.42165868,  0.52094738, -0.74989945,
        -0.58589685,  0.62412028, -0.32536844,  0.45100268, -0.11524075],
       [ 0.15588016, -0.69454673, -0.52302023,  0.30082177, -0.58574652,
         0.46729857,  0.27087785,  0.49305627,  0.12806991,  0.12453312]])

In [83]:
linalg.pinv2(C)

array([[ 0.34329464, -0.01669875, -0.14262709,  0.49251876,  0.46172214,
        -0.45952021, -0.19149618, -0.03849985,  0.17760585,  0.12595034],
       [-0.42474817,  0.34299157,  0.34013561, -0.32326703,  0.10733449,
         0.12515799, -0.36212687,  0.37618471,  0.08544296,  0.12646045],
       [-0.15063371,  0.8040288 , -0.06065989, -0.77883201,  0.79470985,
         0.7765395 , -0.16882859, -0.13195317, -0.61673803,  0.06720802],
       [ 0.34392536, -0.43440415,  0.42165868,  0.52094738, -0.74989945,
        -0.58589685,  0.62412028, -0.32536844,  0.45100268, -0.11524075],
       [ 0.15588016, -0.69454673, -0.52302023,  0.30082177, -0.58574652,
         0.46729857,  0.27087785,  0.49305627,  0.12806991,  0.12453312]])

In [84]:
#creating sparse matrix
F= np.eye(3,k=0)

In [85]:
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
F = np.eye(3,k=1)

In [87]:
F

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [88]:
G = np.mat(np.identity(2))

In [89]:
G

matrix([[1., 0.],
        [0., 1.]])

In [90]:
C = np.mat(np.random.random((10,5)))

In [91]:
C

matrix([[0.67761311, 0.84005415, 0.2838738 , 0.5256231 , 0.00272748],
        [0.74740895, 0.00214711, 0.32972286, 0.91114327, 0.25305743],
        [0.2368543 , 0.69067674, 0.10955467, 0.37345641, 0.65838623],
        [0.65503083, 0.41749477, 0.84045357, 0.08700932, 0.24769604],
        [0.33575703, 0.23922045, 0.06080839, 0.56228809, 0.96690663],
        [0.41779216, 0.27405853, 0.17897476, 0.84827754, 0.95042738],
        [0.76575082, 0.42326319, 0.14430667, 0.28840176, 0.21887239],
        [0.04843944, 0.17727487, 0.84747348, 0.48011438, 0.52516398],
        [0.4490031 , 0.45663642, 0.15215407, 0.73965269, 0.38084745],
        [0.41996446, 0.69193816, 0.10064778, 0.0420735 , 0.90855865]])

In [92]:
C[C>0.5] = 0

In [93]:
C

matrix([[0.        , 0.        , 0.2838738 , 0.        , 0.00272748],
        [0.        , 0.00214711, 0.32972286, 0.        , 0.25305743],
        [0.2368543 , 0.        , 0.10955467, 0.37345641, 0.        ],
        [0.        , 0.41749477, 0.        , 0.08700932, 0.24769604],
        [0.33575703, 0.23922045, 0.06080839, 0.        , 0.        ],
        [0.41779216, 0.27405853, 0.17897476, 0.        , 0.        ],
        [0.        , 0.42326319, 0.14430667, 0.28840176, 0.21887239],
        [0.04843944, 0.17727487, 0.        , 0.48011438, 0.        ],
        [0.4490031 , 0.45663642, 0.15215407, 0.        , 0.38084745],
        [0.41996446, 0.        , 0.10064778, 0.0420735 , 0.        ]])

In [94]:
H = sparse.csr_matrix(C)

In [95]:
H

<10x5 sparse matrix of type '<class 'numpy.float64'>'
	with 31 stored elements in Compressed Sparse Row format>

In [96]:
I = sparse.csc_matrix(D)

In [97]:
I

<2x2 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in Compressed Sparse Column format>

In [98]:
J = sparse.dok_matrix(A)

In [99]:
J

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Dictionary Of Keys format>

In [100]:
E

matrix([[1],
        [2],
        [3]])

In [101]:
sparse.isspmatrix_csc(A)

False

In [102]:
A

matrix([[0.25415886, 0.26913639],
        [0.15352322, 0.54431044]])

In [103]:
np.info(np.matrix)

 matrix()

matrix(data, dtype=None, copy=True)

.. note:: It is no longer recommended to use this class, even for linear
          algebra. Instead use regular arrays. The class may be removed
          in the future.

Returns a matrix from an array-like object, or from a string of data.
A matrix is a specialized 2-D array that retains its 2-D nature
through operations.  It has certain special operators, such as ``*``
(matrix multiplication) and ``**`` (matrix power).

Parameters
----------
data : array_like or string
   If `data` is a string, it is interpreted as a matrix with commas
   or spaces separating columns, and semicolons separating rows.
dtype : data-type
   Data-type of the output matrix.
copy : bool
   If `data` is already an `ndarray`, then this flag determines
   whether the data is copied (the default), or whether a view is
   constructed.

See Also
--------
array

Examples
--------
>>> a = np.matrix('1 2; 3 4')
>>> print(a)
[[1 2]
 [3 4]]

>>> np.matrix([[1, 2], [3, 4]

In [104]:
A

matrix([[0.25415886, 0.26913639],
        [0.15352322, 0.54431044]])

In [105]:
D

matrix([[3, 4],
        [5, 6]])

In [ ]:
A = 

In [106]:
#matrix function

In [108]:
np.add(A,D)

matrix([[3.25415886, 4.26913639],
        [5.15352322, 6.54431044]])

In [109]:
np.subtract(A,D)

matrix([[-2.74584114, -3.73086361],
        [-4.84647678, -5.45568956]])

In [110]:
np.divide(A,D)

matrix([[0.08471962, 0.0672841 ],
        [0.03070464, 0.09071841]])

In [111]:
A@D

matrix([[2.1081585 , 2.63145375],
        [3.18212189, 3.87995556]])

In [112]:
A*D

matrix([[2.1081585 , 2.63145375],
        [3.18212189, 3.87995556]])

In [115]:
np.multiply(A,D)

matrix([[0.76247657, 1.07654555],
        [0.76761612, 3.26586266]])

In [132]:
A = np.mat([[1,1],[1,1]])

In [141]:
A

matrix([[1, 1],
        [1, 1]])

In [133]:
D

matrix([[3, 4],
        [5, 6]])

In [134]:
np.multiply(A,D)

matrix([[3, 4],
        [5, 6]])

In [135]:
np.dot(A,D)

matrix([[ 8, 10],
        [ 8, 10]])

In [136]:
np.vdot(A,D)

matrix([[3]])

In [137]:
np.inner(A,D)

matrix([[ 7, 11],
        [ 7, 11]])

In [138]:
np.outer(A,D)

array([[3, 4, 5, 6],
       [3, 4, 5, 6],
       [3, 4, 5, 6],
       [3, 4, 5, 6]])

In [139]:
np.tensordot(A,D)

array(18)

In [140]:
np.kron(A,D)

matrix([[3, 4, 3, 4],
        [5, 6, 5, 6],
        [3, 4, 3, 4],
        [5, 6, 5, 6]])

In [142]:
#exponential functions
linalg.expm(A)

array([[4.19452805, 3.19452805],
       [3.19452805, 4.19452805]])

In [145]:
#Log
linalg.logm(A)

C:\Users\namrata\Anaconda3\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py:829: LogmExactlySingularWarning: The logm input matrix is exactly singular.
  warnings.warn(exact_singularity_msg, LogmExactlySingularWarning)


array([[-22.67927734,  23.37242452],
       [ 23.37242452, -22.67927734]])

In [146]:
#Trignometric functions
linalg.sinm(D)

array([[-0.07153039,  0.17875259],
       [ 0.22344073,  0.06253405]])

In [147]:
linalg.cosm(D)

array([[ 0.30988067, -0.82893511],
       [-1.03616888, -0.31182066]])

In [148]:
linalg.tanm(D)

array([[-0.21717737,  0.00408362],
       [ 0.00510453, -0.21411465]])

In [149]:
linalg.sinhm(D)

array([[1716.2338286 , 2134.23383225],
       [2667.79229031, 3316.90920278]])

In [150]:
linalg.coshm(D)

array([[1717.05255912, 2133.70712649],
       [2667.13390811, 3317.33290398]])

In [151]:
linalg.tanhm(D)

array([[0.20020645, 0.51458565],
       [0.64323206, 0.58614568]])

In [153]:
linalg.sqrtm(D)

array([[1.03525981+0.30697685j, 1.2872401 -0.19750833j],
       [1.60905012-0.24688541j, 2.00068989+0.15884561j]])

In [154]:
linalg.funm(A,lambda x :x*2)

array([[2., 2.],
       [2., 2.]])

In [155]:
#decompositions
la,v = linalg.eig(A)

In [156]:
l1,l2 = la

In [157]:
la

array([2.+0.j, 0.+0.j])

In [158]:
v

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [160]:
linalg.eig(A)

(array([2.+0.j, 0.+0.j]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [161]:
l1

(2+0j)

In [162]:
l2

0j

In [163]:
v[:,0]

array([0.70710678, 0.70710678])

In [164]:
v[:,1]

array([-0.70710678,  0.70710678])

In [166]:
linalg.eigvals(A)

array([2.+0.j, 0.+0.j])

In [167]:
U,s,Vh = linalg.svd(B)

In [168]:
U

array([[-0.42924656+0.00000000e+00j,  0.90318735+2.00536998e-17j],
       [-0.89766322-9.97403574e-02j, -0.42662118-4.74023528e-02j]])

In [169]:
s

array([9.70641843, 0.88625123])

In [170]:
Vh

array([[-0.08532581-0.45837154j, -0.05137856-0.55085295j,
        -0.06165427-0.68755731j],
       [ 0.8051644 +0.1127107j , -0.2674318 -0.36866654j,
        -0.32091816+0.16906606j],
       [-0.08039483+0.33934981j, -0.67869962-0.16078966j,
         0.61917957-0.09224182j]])

In [171]:
M,N = B.shape

In [172]:
M

2

In [173]:
N

3

In [174]:
Sig = linalg.diagsvd(s,M,N)

In [175]:
Sig

array([[9.70641843, 0.        , 0.        ],
       [0.        , 0.88625123, 0.        ]])

In [182]:
P,L,U = linalg.lu(A)

In [183]:
A

matrix([[1, 1],
        [1, 1]])

In [184]:
P

array([[1., 0.],
       [0., 1.]])

In [185]:
L

array([[1., 0.],
       [1., 1.]])

In [186]:
U

array([[1., 1.],
       [0., 0.]])

In [187]:
la, v =sparse.linalg.eigs(F,1)

In [188]:
la

array([-1.69255174e-06-2.93159317e-06j])

In [189]:
v

array([[-1.00000000e+00+4.96187312e-12j],
       [ 1.69255174e-06+2.93159317e-06j],
       [ 5.72952796e-12-9.92374625e-12j]])

In [190]:
sparse.linalg.svds(H,2)

(array([[ 0.05296549,  0.06732433],
        [-0.00133125,  0.15103854],
        [-0.10956504,  0.21976881],
        [-0.31929411,  0.31003282],
        [ 0.25617928,  0.29415376],
        [ 0.34797365,  0.37784967],
        [-0.48788772,  0.38455935],
        [-0.50156743,  0.22483332],
        [ 0.20546067,  0.59102346],
        [ 0.40584205,  0.22626238]]),
 array([0.65935915, 1.21615871]),
 array([[ 0.67313811, -0.27034948,  0.12459505, -0.65691292, -0.16351678],
        [ 0.55910822,  0.63823236,  0.28507435,  0.27744962,  0.34901543]]))